### ISSUE TITLE
Any plans for nested pages

### ISSUE THREAD

**Issue by liamb13** [nuotsu/sanitypress#11]
Could be nice to have the option for deeply nested pages. 

As an example:

- /services
  - /services/branding
  - /services/design
    - /services/design/ui-design

**Comment by nuotsu** [comment]
Thanks for the great suggestion. I may have to make a switch to use Optional Catch-all Segments in Next.js routing, but I do see the value in having nested routing implemented natively.

I'll make sure to have documentation once I have a stable solution for this

**Comment by liamb13** [comment]
Just spent a while playing around with the Studio experience, based on all the different approaches people have tried. Shout outs to: [René](https://www.sanity.io/schemas/unlimited-nesting-13d6dc3e), [Emma](https://www.youtube.com/watch?v=mkbPxE8pCJ8), [Simeon](https://www.sanity.io/guides/parent-child-taxonomy), and [Mathieu](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1716904442428469).

I landed on this:
<img width="1536" alt="image" src="https://github.com/nuotsu/sanitypress/assets/69778531/b7a01188-09fe-4152-ac9f-4b2e6ac5d708">

Found it's a nice middle ground between displaying a hierarchy and not ending up with endless nesting.

Feel free to use what you like, although it still needs some clean up: https://github.com/liamb13/sanitypress/commit/301c7e4ae6c9ae309e3ef274837211bd3dd83a29

**Comment by nuotsu** [comment]
I do like this approach and the way it's organized in the Studio, but do feel like it adds a bit more complexity than I'd like to this "starter" template.

I just published [an article on nested routes](https://sanitypress.dev/blog/a-guide-for-nested-routes). I've provided 2 options for now and mentioned the above setup in the article—I'll let users decide which method they'd prefer to use.

**Comment by westis** [comment]
> Just spent a while playing around with the Studio experience, based on all the different approaches people have tried. Shout outs to: [René](https://www.sanity.io/schemas/unlimited-nesting-13d6dc3e), [Emma](https://www.youtube.com/watch?v=mkbPxE8pCJ8), [Simeon](https://www.sanity.io/guides/parent-child-taxonomy), and [Mathieu](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1716904442428469).
> 
> I landed on this: <img alt="image" width="1536" src="https://private-user-images.githubusercontent.com/69778531/342440540-b7a01188-09fe-4152-ac9f-4b2e6ac5d708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTg3NzcsIm5iZiI6MTcyODMxODQ3NywicGF0aCI6Ii82OTc3ODUzMS8zNDI0NDA1NDAtYjdhMDExODgtMDlmZS00MTUyLWFjOWYtNGIyZTZhYzVkNzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE2Mjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZjA5ZmQwZTNmMjE2MTcxODc5OWEwOWQ5MzNiODA4MGYyZTA1ZWFhYzQ1OTk1NWVhMmEwNDA5YzhlYjJiNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ce3rn5byez8WgZ3FerGV70gBrVYk05nsYUhL57pGD34">
> 
> Found it's a nice middle ground between displaying a hierarchy and not ending up with endless nesting.
> 
> Feel free to use what you like, although it still needs some clean up: [liamb13@301c7e4](https://github.com/liamb13/sanitypress/commit/301c7e4ae6c9ae309e3ef274837211bd3dd83a29)
> 
> One change I haven't got around to is separating the auto-generated slug from an editable slug. I think it'd be nice to still have the option to change the current documents slug, and still have an auto-generated version with all the prefixing.
> 
> So for the document `/services/design/ui-design`, the `ui-design` part could be edited or generated from the title, but the `/services/design/`would be read-only.

@liamb13 
How does your navigation look like then? That is, if you have nested pages, can only parent pages be selected in the navigation and its children automatically appear under it?
