### ISSUE TITLE
Usage of Sanity CLI within the project

### ISSUE THREAD

**Issue by triwats** [nuotsu/sanitypress#18]
First off, love the project. Great way to get to grips quickly in a considered opinionated way.

Do you have any thoughts about the use of Sanity CLI from this project, and how you do standard commands yourselves (nothing in the package.json)? I  setup most of this from scratch and change the configuration file. Since the project is opinionated, I was not sure if this was by design.

By making this slightly easier, it could increase the frequency of Issues here on Github. 
 
If this just an oversight I would be happy to make a PR to make this a little easier!

**Comment by nuotsu** [comment]
@triwats Thanks for your message!
If you're referring to the main [CLI commands](https://www.sanity.io/docs/cli-reference#8b3f87b2240f) I personally haven't found the need to use these much. Maybe I haven't exposed to common use cases for them.

I'm more than happy to see any suggestions or review PRs 👀
