### ISSUE TITLE
Estimated Read Time Doesn't seem Accurate

### ISSUE THREAD

**Issue by NateDogg97** [nuotsu/sanitypress#21]
After some digging it looks like the readTime property of a blog post object get calculated on line 34 of sanitypress/src/app/(frontend)/blog/[slug]/page.tsx

`'readTime': length(pt::text(body)) / 200,`

This appears to be calculating readTime based on the number of CHARACTERS, not words. Would you like me to submit a pull request to try to fix this?

**Comment by nuotsu** [comment]
Thanks for the input! Definitely, feel free to submit a PR and I'll take a look

**Comment by nuotsu** [comment]
Merged https://github.com/nuotsu/sanitypress/pull/23
