### ISSUE TITLE
Pricing's Base not allowed to be empty

### ISSUE THREAD

**Issue by triwats** [nuotsu/sanitypress#28]
* There is a bug with the Pricing Module - which does not handle empty values as it should
* The Pricing Sanity schema should allow for empty values for pricing 
* The Pricing Module should allow empty values

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/fd1ca6db-6201-4165-a1e4-228e5e736f7b">

The Schema has a tip to allow for empty values:

```
...
			fields: [
				defineField({
					name: 'base',
					type: 'number',
					description: '0 for free, empty to hide',
				}),
				defineField({
					name: 'strikethrough',
					type: 'number',
				}),
				defineField({
					name: 'suffix',
					type: 'string',
					placeholder: 'e.g. /mo, per seat, forever, etc.',
				}),
			],
```

The Pricing Type does not have `base` as optional in it's defintion: 

```
...
		type Pricing = SanityDocument<{
			title: string
			highlight?: string
			price: {
				base?: number
				strikethrough?: number
				suffix?: string
			}
			ctas?: CTA[]
			content?: any
		}>
```

**Comment by nuotsu** [comment]
Thanks for catching this and submitting a PR! Left a minor comment, if you can take a look 👍

**Comment by triwats** [comment]
Hey @nuotsu , I cannot find the comment! I tried to reach out via Slack (sanity.io land).

**Comment by nuotsu** [comment]
@triwats In the PR sorry! https://github.com/nuotsu/sanitypress/pull/29

I'm currently away from home and from slack so I missed your message 🙏
