### ISSUE TITLE
404 Not found when deploying with Vercel

### ISSUE THREAD

**Issue by markusjs** [nuotsu/sanitypress#3]
I get this error when I have deployed with Vercel. I have added the Sanity ID and Token. 

<img width="767" alt="image" src="https://github.com/nuotsu/next-sanity-template/assets/19786812/c4c7c6b9-1c4c-4bba-ab9c-c45e1a9e1ac5">

**Comment by nuotsu** [comment]
Hi we're you able to resolve? I may need more context for this...

**Comment by kingsthecrypto** [comment]
I'm getting the same exact error.

**Comment by kingsthecrypto** [comment]
![image](https://github.com/nuotsu/sanitypress/assets/162418789/b5904391-e9d6-428b-b4b9-c2d345a09608)

**Comment by nuotsu** [comment]
In your Sanity Studio, you'll need to create a new "Page" document with the slug `index` in order to establish a Homepage for your site, as mentioned in the [Docs](https://arc.net/l/quote/xaseoyny).

You may also need to publish a "Site" singular document as well.

**Comment by buckspencer** [comment]
I am getting the same error. 

My app is running in Vercel and I can access the studio from the deployed URL with a created Home page with slug 'index' and a 404 page with slug '404'. 

Perhaps you can make a data dump of the sample site for people to preload their Sanity datasets with?

<img width="1266" alt="Screenshot 2024-06-08 at 11 30 07 AM" src="https://github.com/nuotsu/sanitypress/assets/5303892/096e1387-c7f4-498f-bc84-c0e3d3ebd2e5">

**Comment by buckspencer** [comment]
Got it working. 
I think what I missed before was setting the root. 
<img width="352" alt="Screenshot 2024-06-08 at 12 07 30 PM" src="https://github.com/nuotsu/sanitypress/assets/5303892/f830a8af-5b16-4bd4-9351-9ee8ff7d491d">

Now my Vercel settings looks like this and it works.
<img width="837" alt="Screenshot 2024-06-08 at 12 01 04 PM" src="https://github.com/nuotsu/sanitypress/assets/5303892/29c3a941-8d8a-4cb4-bb63-2d0878ac9307">

**Comment by nuotsu** [comment]
Thanks @buckspencer for providing this. I will update the documentation to mention this.
