### ISSUE TITLE
Issues Building against a Private Dataset

### ISSUE THREAD

**Issue by kennethwyu** [nuotsu/sanitypress#31]
Thanks for building this great starter template!

I've been running into an issue on build (both local + Vercel) and when testing out redirects using a private dataset -- it appears that the token is missing from the Sanity client declaration in a few places:

https://github.com/nuotsu/sanitypress/blob/e17f92e279fd37cbdcd777adf288b6fbbf09dced/src/lib/sanity/fetch.ts#L35-L40

https://github.com/nuotsu/sanitypress/blob/e17f92e279fd37cbdcd777adf288b6fbbf09dced/next.config.ts#L4-L9

Adding `token: process.env.NEXT_PUBLIC_SANITY_TOKEN` seems to have resolved it. Is this expected behavior?

These build failures manifested as a different error (e.g. Missing 'site' document in Sanity Studio) which could be misleading when trying to debug.

**Comment by mitchuman** [comment]
@kennethwyu Hi thanks for noticing this! (I haven't used private datasets before)

I've updated the codebase to add some documentation for `token` (7b86c05056f139b67444bf8aa4864405a365d764)
