### ISSUE TITLE
https://sanitypress.dev/sitemap.xml

### ISSUE THREAD

**Issue by alioftech** [nuotsu/sanitypress#34]
Hey guys,

Is there an issue with the sitemap.xml? It is not accessible neither for your website or ours.

**Comment by nuotsu** [comment]
@alioftech Thanks for bringing this to attention. This is definitely a bug, but with an easy fix.

Please move `src/app/(frontend)/sitemap.ts` to `src/app/sitemap.ts` (the root /app directory). It seems Next.js won't generate a sitemap.xml if it's under a grouped route.

You can reference this recent commit: d816d0f6e5f475018c662744d0e6f2776a7fffbe
