### ISSUE TITLE
Build fails deploying to Vercel

### ISSUE THREAD

**Issue by lukeoly** [nuotsu/sanitypress#35]
I'm getting this error when deploying a fresh 5.0 install to Vercel:

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at n (/vercel/path0/.next/server/chunks/1206.js:7:465)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Export encountered an error on /(frontend)/page: /, exiting the build.
 ⨯ Static worker exited with code: 1 and signal: null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
```

**Comment by mitchuman** [comment]
@lukeoly Have you added the required Studio documents, found on **step 4** of the [Getting Started](https://arc.net/l/quote/qpyswdyw) docs?

| Document | Slug     | Use             | Required? |
| -------- | -------- | --------------- | --------- |
| `site`   |          | Global settings | ✅        |
| `page`   | `index`  | Homepage        | ✅        |
| `page`   | `404`    | Page not found  |           |
| `page`   | `blog`   | Blog listing    |           |
| `page`   | `blog/*` | Blog post       |           |

**Comment by lukeoly** [comment]
@mitchuman 
Yes I have. Also, the error above is not present when running the build locally.
![Screenshot 2024-11-08 at 12 37 04 PM](https://github.com/user-attachments/assets/33cf0d44-26b3-4b05-b184-7228ce36edeb)

**Comment by nuotsu** [comment]
@lukeoly I see you are using yarn. Can you try with npm?

And you've made zero changes in the codebase? Just add the demo data?

**Comment by lukeoly** [comment]
Swapping to npm didn't fix it but I've started again with fresh repo, new sanity poject and new vercel instance and the deployment is working again. So strange. 

Thank you for your help on this and for this project starter ❤️

**Comment by kittst** [comment]
Hi @mitchuman,

I'm getting a very similar error when trying to deploy on Vercel, even after importing the demo site data. It works locally though. Things I've also tried:

1. Restarting with a fresh repo like @lukeoly did, but I get the same error.
2. Opening Sanity studio locally and publishing updates on each of the `site` and `page` documents.
3. Setting `NEXT_PUBLIC_SANITY_PROJECT_ID` and `NEXT_PUBLIC_SANITY_DATASET` to the correct values (from Sanity, same as ones used locally)
4. 

Questions
1. Is there more to publishing than just clicking publish at the bottom of each document? 
2. What is `PUBLIC_BASE_URL` supposed to be for Vercel? For local development, I had to set this to `http://localhost:3000/`
3. (offtopic) What does `NEXT_PUBLIC_GITHUB_TOKEN` refer to? 

Any help is appreciated. Thanks for creating and open sourcing this! Hoping I can get it deployed and live! 

Error: 
```
   Collecting page data ...
   Generating static pages (0/11) ...
   Generating static pages (2/11) 
   Generating static pages (5/11) 
   Generating static pages (8/11) 
Error occurred prerendering page "/blog/sample-blog-post". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at l (/vercel/path0/.next/server/chunks/4426.js:39:521)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Export encountered an error on /(frontend)/blog/[slug]/page: /blog/sample-blog-post, exiting the build.
 ⨯ Static worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1
```

**Comment by nuotsu** [comment]
@kittst 

> `Error occurred prerendering page "/blog/sample-blog-post". Read more: https://nextjs.org/docs/messages/prerender-error`

Regarding your deployment issue, confirming you have `page` documents with slug: `blog` and `blog/*`? These are used for the blog listing page and blog post templates, respectively ([reference](https://sanitypress.dev/docs/getting-started#4-add-content)).

> 1. Is there more to publishing than just clicking publish at the bottom of each document?

Just hitting publish should do the trick, thanks to the new Sanity Live API. A Vercel deploy should reset the cache to publish content as well.

> 2. What is `PUBLIC_BASE_URL` supposed to be for Vercel? For local development, I had to set this to `http://localhost:3000/`

I've updated the README for this to say: `NEXT_PUBLIC_BASE_URL` instead (prepended "NEXT_"). You should set your final website domain to this; e.g. "https://sanitypress.dev"

> 3. (offtopic) What does `NEXT_PUBLIC_GITHUB_TOKEN` refer to?

This is used in the Reputation component (shows github star and fork counts on Hero modules).
