### ISSUE TITLE
GIF Support for Images

### ISSUE THREAD

**Issue by alioftech** [nuotsu/sanitypress#38]
Sanity allows to upload GIFs which are great video alternatives for blogs.
Sanitypress does not seem to support this file format.
Is it possible to fix this?
![Skjermbilde 2024-12-06 kl  07 51 12](https://github.com/user-attachments/assets/d67d1dbc-6513-4ac0-9752-2fb662f4b350)

**Comment by mitchuman** [comment]
@alioftech Do you have a sample URL for an uploaded GIF?

I am not able to replicate on my end... I've uploaded a .gif and seems to be displaying. I did see it does take a second to load however:
- [no image options](https://cdn.sanity.io/images/elyfelq1/production/49571520820ded308be2013431ad900cedf41cfc-350x197.gif)
- [`width=400`](https://cdn.sanity.io/images/elyfelq1/production/49571520820ded308be2013431ad900cedf41cfc-350x197.gif?w=400)
- [`width=400&auto=format`](https://cdn.sanity.io/images/elyfelq1/production/49571520820ded308be2013431ad900cedf41cfc-350x197.gif?w=400&auto=format)

```
https://cdn.sanity.io/images/elyfelq1/production/49571520820ded308be2013431ad900cedf41cfc-350x197.gif
https://cdn.sanity.io/images/elyfelq1/production/49571520820ded308be2013431ad900cedf41cfc-350x197.gif?w=400
https://cdn.sanity.io/images/elyfelq1/production/49571520820ded308be2013431ad900cedf41cfc-350x197.gif?w=400&auto=format
```

<img src="https://cdn.sanity.io/images/elyfelq1/production/49571520820ded308be2013431ad900cedf41cfc-350x197.gif?w=400&auto=format" />

**Comment by alioftech** [comment]
I’m using the hero section. There it does not load

**Comment by mitchuman** [comment]
@alioftech I've test all Hero modules and browsers (macOS and Window) and they all show the .gif properly. Can you provide some additional context (eg. OS, website URL—if you are comfortable sharing, etc)

<img width="1348" alt="Screenshot 2024-12-09 at 11 29 19 AM" src="https://github.com/user-attachments/assets/156e1fba-401e-4a4a-8ae8-27a7eaa195e3">
