### ISSUE TITLE
Error in Dev:  

### ISSUE THREAD

**Issue by Brettkgamble** [nuotsu/sanitypress#41]
Upgraded to SanityPress 5.4.0
Ran yarn install and yarn run dev:turbopack and received the error below.  Deleted .next and node_modules and tried again. Same error.

Build Error
Next.js (15.1.0) (Turbopack)
Failed to compile

./src/sanity/lib/fetch.ts:4:1
Ecmascript file had an error
  2 | import { token } from '@/sanity/lib/token'
  3 | import { dev } from '@/lib/env'
> 4 | import { draftMode } from 'next/headers'
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  5 | import { defineLive, type QueryOptions } from 'next-sanity'
  6 | import type { QueryParams } from 'sanity'
  7 |

You're importing a component that needs "next/headers". That only works in a Server Component which is not supported in the pages/ directory. Read more: https://nextjs.org/docs/app/building-your-application/rendering/server-components
This error occurred during the build process and can only be dismissed by fixing the error.

**Comment by nuotsu** [comment]
@Brettkgamble Looks like this is more of a Next.js error, judging from the provided error message. Looks like you are young the `pages/` directory rather than the `app/` router.

**Comment by Brettkgamble** [comment]
Right....but no. I have made no changes to your code at all. To me I am
thinking it is a Sanity issue....

**Comment by mitchuman** [comment]
Can you please try adding `'use server'` at the top of your `src/sanity/lib/fetch.ts` file? (This has been a new addition since updating to Next.js 15.1)

And make adjustments to _your_ file to match the latest version of this file in SanityPress v5.4.0:
> https://github.com/nuotsu/sanitypress/blob/main/src/sanity/lib/fetch.ts#L1

**Comment by Brettkgamble** [comment]
The suggested changes worked.  FYI....this issue was due to my way of updating my code base which somehow meant I missed a couple of files from 5.4.0.  The changes you suggested worked with another minor change in the import of Groq in queries.ts.

I appreciate your assistance and this issue can be closed.  I will make sure I get better at this, fork the repo, pull updates from main rather than unpack the zip......

**Comment by mitchuman** [comment]
I'm glad that fixed it! I will work to make better documentation on the upgrading process to avoid future mishaps like this! Thanks again for reporting this 🖤
