### ISSUE TITLE
Demo data

### ISSUE THREAD

**Issue by AnasGamal** [nuotsu/sanitypress#7]
Is there a place where I can find the demo data to get my site to look the same as a starting point? I couldn't find in the documentation or README file

**Comment by nuotsu** [comment]
@AnasGamal Not at the moment, but I can definitely add some screenshots on the demo site. You can expect to see that in the coming day or two

**Comment by mitchuman** [comment]
Screenshots have been uploaded here:
https://sanitypress.vercel.app/studio-screenshots
